version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dockerdb
      - SPRING_DATASOURCE_USERNAME = dockeruser
      - SPRING_DATASOURCE_PASSWORD = dockerpassword
      - SPRING_JPA_HIBERNATE_DDL-AUTO= VALIDATE
      - TOKEN_SECRET_KEY=
      - TOKEN_EXPIRATIONS=

    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=